In [ ]:
s="hi there kamal"

In [ ]:
print (s)

hi there kamal


In [ ]:
planet="mars"

In [ ]:
diameter=56467

In [ ]:
print('diameter of {} is {} kilometers'.format(planet,diameter));

diameter of mars is 56467 kilometers


In [ ]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [ ]:
print(d['k1'][3]["tricky"][3]["target"][2])

3


In [ ]:
import numpy as np

In [ ]:
x=np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
arr=np.arange(20,36,2)
print("array of all even numbers from 20 to 36")
print(arr)

array of all even numbers from 20 to 36
[20 22 24 26 28 30 32 34]


In [ ]:
arr=np.ones(10)*5
print("array of 10 fives")
print (arr)

array of 10 fives
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
a=np.array([1,2,3])
print(a)
b=np.array([4,5,6])
print(b)
print("concate of a & b")
print(np.concatenate((a,b)))

[1 2 3]
[4 5 6]
concate of a & b
[1 2 3 4 5 6]


In [ ]:
string="hello there mate"
words=string.split(',')
print(words)

['hello there mate']
